In [9]:
#task1:
names1=['albert','james','nikola']
names2=['einstein','watt','tesla']
result=lambda x,y:x.title()+' '+y.title()
print(list(map(result,names1,names2)))

['Albert Einstein', 'James Watt', 'Nikola Tesla']


In [6]:
#multilevel inheritance:  (grandfather--->father---->child)
class A:
    def classA():
        print("iam from class a")
class B(A):
    def classB():
        print("iam from class b")
class C(B):
    def classC():
        print("iam from class c")
        
obj=C
obj.classA()
obj.classB()
obj.classC()

iam from class a
iam from class b
iam from class c


In [7]:
#hyrarical inheritance: (single parent multiple childs)
class A:
    def classA():
        print("iam from class a")
class B(A):#b,a
    def classB():
        print("iam from class b")
class C(A): #c,a
    def classC():
        print("iam from class c")
        
obj=C
obj1=B
obj.classA()
obj1.classB()
obj.classC()

iam from class a
iam from class b
iam from class c


In [8]:
#hybrid inheritance
#(all types of inheritances)
#-Hybrid inheritance is a combination of multiple and multilevel inheritance. 
'''
 ex:    father mother
              |
        ------------
      child(grandfather)
              |      
        child(father)
              |
        grandchild(son)
'''
    
class A:
    def classA():
        print("iam from class a")
class B:
    def classB():
        print("iam from class b")
class C(A,B):
    def classC():
        print("iam from class c")
class D(C):
    def classD():
        print("iam from class d") 
class E(D):
    def classE():
        print("iam from class e") 
        
obj=E
obj.classA()
obj.classB()
obj.classC()
obj.classD()
obj.classE()

iam from class a
iam from class b
iam from class c
iam from class d
iam from class e


In [ ]:
# oop's (continution....)
# packages and modules using oop's:

In [ ]:
# packages(folder):collection of modules
# modules(.py file): collection of functions and classes

In [5]:
from packages.sample import Calsi
obj=Calsi
print(obj.add(5,5))
print(obj.sub(5,5))
print(obj.mul(5,5))
print(obj.div(5,5))
print(obj.mod(5,5))

10
0
25
1.0
0


In [3]:
from packages.sample import *
obj1=Math
print(obj1.power(2,3))
print(obj1.even(5))
print(obj1.even(6))

8
odd
even


In [3]:
from packages.sample import *
obj2=Calsi123(5,7)
print(obj2.__add__())
print(obj2.__mul__())

12
35


# datascience:
- orginising, processing, analysing the huge amount of data.
- data visualization
- extracting the data from the source
- nearly 20 python libraries for datascience
### 3 :
- numpy
- pandas
- matplotlib

### numpy(numerical python):
- it is a fundamental package for scientific computing in python.
- numpy is a python library
- it is used to creat multi dimensional arrays for fast operations
- for installing numpy----->pip install numpy
- import numpy as np

In [5]:
# 1 dimensional array:
import numpy as np
array1d=np.array([2,3,3,4,5])
print(array1d)
print(type(array1d))

[2 3 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# 2 dimensional array:
import numpy as np
array2d=np.array([[2,3,3],[4,5,6]])
print(type(array2d))
array2d

<class 'numpy.ndarray'>


array([[2, 3, 3],
       [4, 5, 6]])

In [12]:
import numpy as np
array2d=np.array([[2,3,3,7,8],[4,5,6]])
print(type(array2d))
array2d

<class 'numpy.ndarray'>


array([list([2, 3, 3, 7, 8]), list([4, 5, 6])], dtype=object)

In [14]:
import numpy as np
l=[2,3,4,'a','b']
print(type(l))
a1=np.array(l)
print(type(a1))
a1

<class 'list'>
<class 'numpy.ndarray'>


array(['2', '3', '4', 'a', 'b'], dtype='<U11')

In [15]:
import numpy as np
a=np.arange(15)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [16]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(type(a))
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
import numpy as np
a=np.arange(15).reshape(4,10)
print(a)
print(type(a))
a

ValueError: cannot reshape array of size 15 into shape (4,10)

In [18]:
# if the array size is too large,then numpy will skips the middle lements with  ...
import numpy as np
a=np.arange(10000)
print(a)
print(type(a))
a

[   0    1    2 ... 9997 9998 9999]
<class 'numpy.ndarray'>


array([   0,    1,    2, ..., 9997, 9998, 9999])

In [19]:
import numpy as np
a=np.arange(10000).reshape(100,100)
print(a)
print(type(a))
a

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
<class 'numpy.ndarray'>


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [20]:
print(dir(np),end=" ")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [22]:
import numpy as np
np.__version__

'1.16.4'

In [24]:
np.array([1,3,4,12,56],dtype='int')

array([ 1,  3,  4, 12, 56])

In [25]:
np.array([1,3,4,12,56],dtype='float')

array([ 1.,  3.,  4., 12., 56.])

In [27]:
np.array([range(i,i+3) for i in [2,4,6]])  #range(2,5)---->2,3,4
                                           #range(4,7)---->4,5,6
                                           #range(6,9)---->6,7,8

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.ones((3,5),dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.full((3,5),56.78)

array([[56.78, 56.78, 56.78, 56.78, 56.78],
       [56.78, 56.78, 56.78, 56.78, 56.78],
       [56.78, 56.78, 56.78, 56.78, 56.78]])

In [34]:
#evenly spaced values
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [35]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [46]:
import random
random.randint(000000,999999)

490420

In [50]:
np.random.randint(1,50,size=(4,4))

array([[ 7, 48, 43, 48],
       [29, 47, 27, 44],
       [ 6, 12, 24, 30],
       [49, 32, 26, 32]])

In [51]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
d=np.array([2,3,4,5])
np.diag(d)

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [54]:
d=np.array([2,3,4,5]*3)
d

array([2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5])

In [55]:
d=np.repeat([2,3,4,5],3)
d

array([2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [56]:
a=np.array([0,1,2])
b=np.array([5,5,5])
a+b

array([5, 6, 7])

In [57]:
a*3

array([0, 3, 6])

In [ ]:
# nd arrays:
1)ndim
2)shape
3)size
4)dtype
5)itemsize

In [64]:
a=np.array([[1,2,3],[2,3,4]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize) # returns the size in bytes

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6
int32
4


In [65]:
a[::-1]

array([[2, 3, 4],
       [1, 2, 3]])

In [68]:
n1=np.arange(1,5).reshape(2,2)
n2=np.arange(5,9).reshape(2,2)
print(n1)
print(n2)
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1%n2)
print(n1//n2)
print(n1**n2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]
[[0 0]
 [0 0]]
[[    1    64]
 [ 2187 65536]]


In [69]:
print(n1)
print(n2)
print(n1.dot(n2)) #matrix multiplication

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [70]:
x=np.array([2,4,1,5,3])
np.sort(x)

array([1, 2, 3, 4, 5])

In [76]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[[1 2 3]
 [4 5 6]]
1
6
21
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [77]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.max(axis=0)) # row max 
print(a.max(axis=1)) #column max

[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 6]


In [80]:
a=np.array([2,3,4,5,2])
print(a[0])
print(a[3])
print(a<3)

2
5
[ True False False False  True]


In [82]:
a=np.arange(3)
print(a)
b=np.arange(4)[:,np.newaxis]
print(b)

[0 1 2]
[[0]
 [1]
 [2]
 [3]]


In [85]:
n=np.ones((3,3),dtype="int")
print(n)
np.vstack((n,np.array((2,2,2))))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
# vstack
[[1 1 1]
 [1 1 1]
 [1 1 1]]      +[[2,2,2]]

In [ ]:
# hstack
[[1 1 1]
 [1 1 1]
 [1 1 1]]      +[[2,
                  2,
                  2]]

In [90]:
a=np.ones((3,3),dtype="int")
b=np.array((2,2,2)).reshape(3,1)
print(a)
print(b)
np.hstack((a,b))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2]
 [2]
 [2]]


array([[1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 1, 2]])