### Constructor

In [3]:
class Math:
    def add(n1,n2):
        return n1+n2
    def mul(n1,n2):
        return n1*n2
obj = Math
print(obj.add(12,13))
print(obj.mul(3,4))

25
12


In [6]:
class Math:
    def __init__(self,n1,n2):
        self.n1 = n1
        self.n2 = n2
    def show(self):
        print(self.n1)
        print(self.n2)
    def add(self):
        print(self.n1+self.n2)
        
obj = Math(5,3)
obj.show()
obj.add()

5
3
8


In [8]:
# User defined constructor
class Math:
    def __init__(abc,n1,n2):
        abc.n1 = n1
        abc.n2 = n2
    def show(abc):
        print(abc.n1)
        print(abc.n2)
    def add(abc):
        print(abc.n1+abc.n2)
        
obj = Math(5,3)
obj.show()
obj.add()

5
3
8


### Hot to define packages and modules using OOPs
- import myModule
- from myModule import Calsi
- from myModule.Calsi import add
- from myModule.Calsi import*

In [7]:
# import myModule
import myModule
obj = myModule.Calsi
print(obj.add(5,3))

8


#### For Data Analysis
    * Numpy, pandas, matplotlib...etc
- Numpy --> Numerical Python
- Numpy is a python library used for working with arrays.

In [9]:
import numpy as np

In [11]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [12]:
np.__version__ # checking the version of numpy

'1.18.5'

In [13]:
# create 1D array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [28]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)
print(a2.size)

[[1 2 3]
 [4 5 6]]
6


In [22]:
# creating 3D array
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
# pre defined functions in array
print(type(a3))
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.itemsize)
print(a3.dtype)

<class 'numpy.ndarray'>
3
(1, 3, 3)
9
4
int32


#### Creating an array using range()
    * Syntax : np.array(range())

In [30]:
r1 = np.array(range(9))
print(r1)

[0 1 2 3 4 5 6 7 8]


In [31]:
r1 = np.array(range(1,10))
print(r1)

[1 2 3 4 5 6 7 8 9]


In [32]:
r1 = np.array(range(1,10,2))
print(r1)

[1 3 5 7 9]


In [33]:
# arange
a1 = np.arange(9)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
# arange.reshape()
a2 = np.arange(1,10).reshape(3,3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
a2 = np.arange(10,40).reshape(5,6)
print(a2)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]
 [34 35 36 37 38 39]]


In [39]:
# using linspace
print(np.linspace(10,20,5)) # Partitioning the ranging with 3rd argument
print(np.linspace(10,20))

[10.  12.5 15.  17.5 20. ]
[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [43]:
# Creating an array with 0's, 1's and full
o = np.ones((3,3),dtype=int)
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
o*4

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [46]:
z = np.zeros((3,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
f = np.full((2,3),8)
f

array([[8, 8, 8],
       [8, 8, 8]])

In [48]:
np.diag(z) # gives diagonal elements of array

array([0, 0, 0])

In [50]:
np.eye(4,dtype=int) # creating identity matrix

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [51]:
np.eye(4,7,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0]])

### Random
- It generates random values in a range

In [63]:
r = np.random.random()
r

0.015645506685435406

In [60]:
r = np.random.random(9)
r

array([0.40790574, 0.14177097, 0.75027506, 0.41845142, 0.85804449,
       0.13250288, 0.27607164, 0.17756645, 0.44626416])

In [66]:
np.random.randint(10,20)

11

In [68]:
np.random.randint(10,20,3)

array([10, 16, 12])

In [69]:
np.random.randint(10,20,9).reshape(3,3)

array([[19, 18, 19],
       [15, 14, 12],
       [17, 16, 11]])

In [70]:
np.random.randint(10,20,(3,3))

array([[19, 19, 17],
       [15, 12, 17],
       [17, 10, 13]])

In [81]:
r = np.random.randn(5,6)
r.dtype

dtype('float64')

In [82]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl