### Numpy

In [1]:
import numpy as np

In [5]:
a1 = np.arange(11,20).reshape(3,3)
print(a1)
print('..........')
a2 = np.arange(1,10).reshape(3,3)
print(a2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
..........
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Arithmetic Operation
print(a1+a2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [7]:
print(a1-a2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [8]:
print(a1*a2)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [9]:
print(a1/a2)

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]


In [10]:
print(a1%a2)

[[0 0 1]
 [2 0 4]
 [3 2 1]]


In [12]:
print(np.min(a1))
print(np.max(a1))

11
19


In [13]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [14]:
a1.T

array([[11, 14, 17],
       [12, 15, 18],
       [13, 16, 19]])

#### Scientific Computations

In [23]:
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.cos(90))
print(np.sin(90))
print(np.sqrt(144))
print(np.power(5,1/2))
print(5**(1/2))

15.0
15.0
2.581988897471611
-0.4480736161291701
0.8939966636005579
12.0
2.23606797749979
2.23606797749979


In [28]:
# math methods without using numpy
import math
print(math.sqrt(144))
print(math.pi)

12.0
3.141592653589793


In [29]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [33]:
print(np.log(1))
print(np.log(10))
print(np.log2(10))
print(np.log([1,2,3]))

0.0
2.302585092994046
3.321928094887362
[0.         0.69314718 1.09861229]


In [35]:
print(np.exp(1))
print(np.exp(2))

2.718281828459045
7.38905609893065


In [36]:
# vstack
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [39]:
a = np.array([1,2,3,4,5])
print(np.vstack(a))

[[1]
 [2]
 [3]
 [4]
 [5]]


In [37]:
print(np.vstack(a1))

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [38]:
# hstack
print(np.hstack(a1))

[11 12 13 14 15 16 17 18 19]


### Accessing a particular elements using indexing or slicing
- array[start:end,start:end]

In [40]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [41]:
a1[0:3]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
a1[0:3,0:3]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [43]:
a1[0:2]

array([[11, 12, 13],
       [14, 15, 16]])

In [44]:
a1[0:2,0:2]

array([[11, 12],
       [14, 15]])

In [45]:
a1[0][0]

11

In [46]:
a1[1][1]

15

### Pandas
- Means PanelData
- One of the data science package
- Used for data manipulation, analysis and cleaning
- Contains mainly 2 data structures in it
    1. Series --> is a sequence of data
    2. DataFrame --> is a data with rows and columns

In [47]:
import pandas as pd

In [48]:
pd.__version__

'1.0.5'

1. Series

In [49]:
# create data with series

a = pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [50]:
# Changing the index values in series
s = pd.Series([1,2,3,4,5],index=[1,2,3,4,5])
s

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [51]:
import numpy as np
s = pd.Series([2,4,6,8],index=np.arange(1,5))
s

1    2
2    4
3    6
4    8
dtype: int64

In [53]:
s = pd.Series(['keerthi',221,9.8],index=['str','int','float'])
s

str      keerthi
int          221
float        9.8
dtype: object

In [54]:
# Creating series using dictionaries
dic = {'key1':'keerthi','key2':221,'key3':9.0}
pd.Series(dic)

key1    keerthi
key2        221
key3          9
dtype: object

In [56]:
# Creating data series using tuples
t = (1,2,3,4,5,6)
pd.Series(t,index=[1,2,3,4,5,6])

1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64

In [57]:
# Accessing elements using indexing
s = pd.Series(np.random.randint(20,40,6))
s

0    21
1    31
2    20
3    22
4    25
5    34
dtype: int32

In [58]:
print(s[4])

25


In [59]:
print(s[2:4])

2    20
3    22
dtype: int32


### Converting strings|lists|tuples and dictionaries into DataFrames

In [60]:
# Creating data using DataFrame
a = pd.DataFrame([1,2,3,4,5])
a

0
0  1
1  2
2  3
3  4
4  5

In [61]:
d = 'Hey i am keerthi'.split()
pd.DataFrame(d)

0
0      Hey
1        i
2       am
3  keerthi

In [62]:
# Creating multiple columns in a DataFrame
li = [[1,2,3],[4,5,6]]
pd.DataFrame(li,index=['list1','list2'])

0  1  2
list1  1  2  3
list2  4  5  6

In [63]:
a = [['vijay',12],['keerthi',14],['chaitanya',17]]
data = pd.DataFrame(a)
data

0   1
0      vijay  12
1    keerthi  14
2  chaitanya  17

In [64]:
a = [['vijay',12],['keerthi',14],['chaitanya',17]]
data = pd.DataFrame(a,columns=('Name','Age'),index=np.arange(1,4))
data

Name  Age
1      vijay   12
2    keerthi   14
3  chaitanya   17

In [67]:
# Creating multiple columns using dictionaries

d = {'Name':['keerthi','sireesha','vijaya','sindhu'],'Age':[12,13,14,15],
    'Branch':['CSE','ECE','EEE','CSE']}
data = pd.DataFrame(d,index=np.arange(1,5))
data

Name  Age Branch
1   keerthi   12    CSE
2  sireesha   13    ECE
3    vijaya   14    EEE
4    sindhu   15    CSE

In [68]:
# Converting data series into dataframes
# NaN --> Not a Number
d = {'one':pd.Series([1,2,3],index=['a','b','c']),
    'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
data = pd.DataFrame(d)
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [69]:
# Getting all values in dataframe
data.values

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [nan,  4.]])

In [70]:
# Getting all index values in dataframe

data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [72]:
# Checking null values in a dataframe
data.isnull()

one    two
a  False  False
b  False  False
c  False  False
d   True  False

In [74]:
data.notnull()

one   two
a   True  True
b   True  True
c   True  True
d  False  True

In [75]:
# Accessing a particular column values
data['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [76]:
data['one']['c']

3.0

In [77]:
data[0:3] # Accessing first 3 rows

one  two
a  1.0    1
b  2.0    2
c  3.0    3

In [80]:
data[-1:]

one  two
d  NaN    4

### iloc and loc
- iloc -  for accessing rows using integer indicies
- loc - for accessing rows using other than number indicies

In [81]:
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [83]:
data.iloc[2]

one    3.0
two    3.0
Name: c, dtype: float64

In [84]:
data.loc['c']

one    3.0
two    3.0
Name: c, dtype: float64

In [85]:
data.head()

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [90]:
d = {'one':pd.Series([1,2,3,5,6,7],index=['a','b','c','d','e','f']),
    'two':pd.Series([1,2,3,4,5,6,7,8],index=['a','b','c','d','e','f','g','h'])}
data = pd.DataFrame(d)
data

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  5.0    4
e  6.0    5
f  7.0    6
g  NaN    7
h  NaN    8

In [91]:
data.head() # for accessing first five rows

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  5.0    4
e  6.0    5

In [92]:
data.head(3)

one  two
a  1.0    1
b  2.0    2
c  3.0    3

In [93]:
data.tail() # for accessing last five rows

one  two
d  5.0    4
e  6.0    5
f  7.0    6
g  NaN    7
h  NaN    8

In [94]:
data.tail(2)

one  two
g  NaN    7
h  NaN    8

In [95]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, a to h
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   one     6 non-null      float64
 1   two     8 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 192.0+ bytes


In [96]:
data.describe()

one      two
count  6.000000  8.00000
mean   4.000000  4.50000
std    2.366432  2.44949
min    1.000000  1.00000
25%    2.250000  2.75000
50%    4.000000  4.50000
75%    5.750000  6.25000
max    7.000000  8.00000

In [97]:
a = pd.read_csv('AppleStore.csv')
a

Unnamed: 0          id  \
0              1   281656475   
1              2   281796108   
2              3   281940292   
3              4   282614216   
4              5   282935706   
...          ...         ...   
7192       11081  1187617475   
7193       11082  1187682390   
7194       11087  1187779532   
7195       11089  1187838770   
7196       11097  1188375727   

                                             track_name  size_bytes currency  \
0                                       PAC-MAN Premium   100788224      USD   
1                             Evernote - stay organized   158578688      USD   
2       WeatherBug - Local Weather, Radar, Maps, Alerts   100524032      USD   
3     eBay: Best App to Buy, Sell, Save! Online Shop...   128512000      USD   
4                                                 Bible    92774400      USD   
...                                                 ...         ...      ...   
7192                                              Kubik   126644224      USD   
7193                                  VR Roller-Coaster   120760320      USD   
7194              Bret Michaels Emojis + Lyric Keyboard   111322112      USD   
7195          VR Roller Coaster World - Virtual Reality    97235968      USD   
7196                       Escape the Sweet Shop Series    90898432      USD   

      price  rating_count_tot  rating_count_ver  user_rating  user_rating_ver  \
0      3.99             21292                26          4.0              4.5   
1      0.00            161065                26          4.0              3.5   
2      0.00            188583              2822          3.5              4.5   
3      0.00            262241               649          4.0              4.5   
4      0.00            985920              5320          4.5              5.0   
...     ...               ...               ...          ...              ...   
7192   0.00               142                75          4.5              4.5   
7193   0.00                30                30          4.5              4.5   
7194   1.99                15                 0          4.5              0.0   
7195   0.00                85                32          4.5              4.5   
7196   0.00                 3                 3          5.0              5.0   

         ver cont_rating   prime_genre  sup_devices.num  ipadSc_urls.num  \
0      6.3.5          4+         Games               38                5   
1      8.2.2          4+  Productivity               37                5   
2      5.0.0          4+       Weather               37                5   
3     5.10.0         12+      Shopping               37                5   
4      7.5.1          4+     Reference               37                5   
...      ...         ...           ...              ...              ...   
7192     1.3          4+         Games               38                5   
7193     0.9          4+         Games               38                0   
7194   1.0.2          9+     Utilities               37                1   
7195  1.0.15         12+         Games               38                0   
7196     1.0          4+         Games               40                0   

      lang.num  vpp_lic  
0           10        1  
1           23        1  
2            3        1  
3            9        1  
4           45        1  
...        ...      ...  
7192         1        1  
7193         1        1  
7194         1        1  
7195         2        1  
7196         2        1  

[7197 rows x 17 columns]